/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sat Jan 13 07:52:52 2018. */

#include "event.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t EventRegister_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, EventRegister, events, events, &EventInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t FieldRegister_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, FieldRegister, fields, fields, &google_protobuf_FieldDescriptorProto_fields),
    PB_LAST_FIELD
};

const pb_field_t AnyData_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, AnyData, data, data, &google_protobuf_Any_fields),
    PB_LAST_FIELD
};

const pb_field_t EventInfo_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, EventInfo, id, id, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, EventInfo, name, id, 0),
    PB_FIELD(  3, UENUM   , OPTIONAL, STATIC  , OTHER, EventInfo, type, name, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, CALLBACK, OTHER, EventInfo, address, type, 0),
    PB_FIELD(  7, MESSAGE , OPTIONAL, STATIC  , OTHER, EventInfo, payload, address, &PayloadInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t PayloadInfo_fields[3] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, PayloadInfo, count, count, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, PayloadInfo, data, count, &DataInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t DataInfo_fields[8] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, DataInfo, id, id, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, DataInfo, type, id, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, DataInfo, name, type, 0),
    PB_FIELD( 11, MESSAGE , OPTIONAL, STATIC  , OTHER, DataInfo, unit, name, &UnitInfo_fields),
    PB_FIELD( 12, MESSAGE , OPTIONAL, STATIC  , OTHER, DataInfo, min, unit, &NumericData_fields),
    PB_FIELD( 13, MESSAGE , OPTIONAL, STATIC  , OTHER, DataInfo, max, min, &NumericData_fields),
    PB_FIELD( 14, MESSAGE , OPTIONAL, STATIC  , OTHER, DataInfo, resolution, max, &NumericData_fields),
    PB_LAST_FIELD
};

const pb_field_t UnitInfo_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, UnitInfo, abbreviation, abbreviation, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, UnitInfo, name, abbreviation, 0),
    PB_LAST_FIELD
};

const pb_field_t NumericData_fields[5] = {
    PB_ONEOF_FIELD(num,   1, SINT32  , ONEOF, STATIC  , FIRST, NumericData, signed_integer, signed_integer, 0),
    PB_ONEOF_FIELD(num,   2, UINT32  , ONEOF, STATIC  , UNION, NumericData, unsigned_integer, unsigned_integer, 0),
    PB_ONEOF_FIELD(num,   3, FLOAT   , ONEOF, STATIC  , UNION, NumericData, float32, float32, 0),
    PB_ONEOF_FIELD(num,   4, DOUBLE  , ONEOF, STATIC  , UNION, NumericData, float64, float64, 0),
    PB_LAST_FIELD
};

const pb_field_t StringData_fields[4] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, StringData, short_string, short_string, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, StringData, medium_string, short_string, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, StringData, long_string, medium_string, 0),
    PB_LAST_FIELD
};

const pb_field_t BytesData_fields[6] = {
    PB_FIELD(  1, FIXED_LENGTH_BYTES, OPTIONAL, STATIC  , FIRST, BytesData, single_byte, single_byte, 0),
    PB_FIELD(  2, FIXED_LENGTH_BYTES, OPTIONAL, STATIC  , OTHER, BytesData, double_byte, single_byte, 0),
    PB_FIELD(  3, FIXED_LENGTH_BYTES, OPTIONAL, STATIC  , OTHER, BytesData, short_bytes, double_byte, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, STATIC  , OTHER, BytesData, medium_bytes, short_bytes, 0),
    PB_FIELD(  5, BYTES   , OPTIONAL, STATIC  , OTHER, BytesData, long_bytes, medium_bytes, 0),
    PB_LAST_FIELD
};

const pb_field_t BooleanData_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, BooleanData, value, value, 0),
    PB_LAST_FIELD
};

const pb_field_t EventStream_fields[7] = {
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , FIRST, EventStream, register, register, &EventRegister_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, EventStream, start_time, register, &Timestamp_fields),
    PB_FIELD(  4, MESSAGE , REPEATED, CALLBACK, OTHER, EventStream, events, start_time, &Event_fields),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, EventStream, event_count, events, 0),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, EventStream, stop_time, event_count, &Timestamp_fields),
    PB_FIELD(  7, STRING  , OPTIONAL, STATIC  , OTHER, EventStream, name, stop_time, 0),
    PB_LAST_FIELD
};

const pb_field_t Event_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Event, id, id, 0),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, Event, timestamp, id, &Timestamp_fields),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, Event, sequence, timestamp, 0),
    PB_FIELD(  7, MESSAGE , OPTIONAL, STATIC  , OTHER, Event, payload, sequence, &Payload_fields),
    PB_LAST_FIELD
};

const pb_field_t Timestamp_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Timestamp, sec, sec, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Timestamp, nsec, sec, 0),
    PB_LAST_FIELD
};

const pb_field_t Payload_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, Payload, data, data, &Data_fields),
    PB_LAST_FIELD
};

const pb_field_t Data_fields[5] = {
    PB_ONEOF_FIELD(data_type,   1, MESSAGE , ONEOF, STATIC  , FIRST, Data, numeric_data, numeric_data, &NumericData_fields),
    PB_ONEOF_FIELD(data_type,   2, MESSAGE , ONEOF, STATIC  , UNION, Data, string_data, string_data, &StringData_fields),
    PB_ONEOF_FIELD(data_type,   3, MESSAGE , ONEOF, STATIC  , UNION, Data, bytes_data, bytes_data, &BytesData_fields),
    PB_ONEOF_FIELD(data_type,   4, MESSAGE , ONEOF, STATIC  , UNION, Data, boolean_data, boolean_data, &BooleanData_fields),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(EventInfo, payload) < 65536 && pb_membersize(DataInfo, unit) < 65536 && pb_membersize(DataInfo, min) < 65536 && pb_membersize(DataInfo, max) < 65536 && pb_membersize(DataInfo, resolution) < 65536 && pb_membersize(EventStream, register) < 65536 && pb_membersize(EventStream, start_time) < 65536 && pb_membersize(EventStream, stop_time) < 65536 && pb_membersize(Event, timestamp) < 65536 && pb_membersize(Event, payload) < 65536 && pb_membersize(Data, data_type.numeric_data) < 65536 && pb_membersize(Data, data_type.string_data) < 65536 && pb_membersize(Data, data_type.bytes_data) < 65536 && pb_membersize(Data, data_type.boolean_data) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_EventRegister_FieldRegister_AnyData_EventInfo_PayloadInfo_DataInfo_UnitInfo_NumericData_StringData_BytesData_BooleanData_EventStream_Event_Timestamp_Payload_Data)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(EventInfo, payload) < 256 && pb_membersize(DataInfo, unit) < 256 && pb_membersize(DataInfo, min) < 256 && pb_membersize(DataInfo, max) < 256 && pb_membersize(DataInfo, resolution) < 256 && pb_membersize(EventStream, register) < 256 && pb_membersize(EventStream, start_time) < 256 && pb_membersize(EventStream, stop_time) < 256 && pb_membersize(Event, timestamp) < 256 && pb_membersize(Event, payload) < 256 && pb_membersize(Data, data_type.numeric_data) < 256 && pb_membersize(Data, data_type.string_data) < 256 && pb_membersize(Data, data_type.bytes_data) < 256 && pb_membersize(Data, data_type.boolean_data) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_EventRegister_FieldRegister_AnyData_EventInfo_PayloadInfo_DataInfo_UnitInfo_NumericData_StringData_BytesData_BooleanData_EventStream_Event_Timestamp_Payload_Data)
#endif


/* @@protoc_insertion_point(eof) */
