// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @enum
 */
export enum MessageType{
  PlasmaCreateRequest= 1,
  PlasmaCreateReply= 2,
  PlasmaAbortRequest= 3,
  PlasmaAbortReply= 4,
  PlasmaSealRequest= 5,
  PlasmaSealReply= 6,
  PlasmaGetRequest= 7,
  PlasmaGetReply= 8,
  PlasmaReleaseRequest= 9,
  PlasmaReleaseReply= 10,
  PlasmaDeleteRequest= 11,
  PlasmaDeleteReply= 12,
  PlasmaStatusRequest= 13,
  PlasmaStatusReply= 14,
  PlasmaContainsRequest= 15,
  PlasmaContainsReply= 16,
  PlasmaConnectRequest= 17,
  PlasmaConnectReply= 18,
  PlasmaEvictRequest= 19,
  PlasmaEvictReply= 20,
  PlasmaFetchRequest= 21,
  PlasmaWaitRequest= 22,
  PlasmaWaitReply= 23,
  PlasmaSubscribeRequest= 24,
  PlasmaUnsubscribeRequest= 25,
  PlasmaDataRequest= 26,
  PlasmaDataReply= 27,
  PlasmaNotification= 28
};

/**
 * @enum
 */
export enum PlasmaError{
  OK= 0,
  ObjectExists= 1,
  ObjectNonexistent= 2,
  OutOfMemory= 3,
  ObjectNotSealed= 4,
  ObjectInUse= 5
};

/**
 * @enum
 */
export enum ObjectStatus{
  Local= 1,
  Remote= 2,
  Nonexistent= 3,
  Transfer= 4
};

/**
 * @constructor
 */
export class PlasmaObjectSpec {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaObjectSpec}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaObjectSpec {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
segmentIndex():number {
  return this.bb!.readInt32(this.bb_pos);
};

/**
 * @returns {flatbuffers.Long}
 */
dataOffset():flatbuffers.Long {
  return this.bb!.readUint64(this.bb_pos + 8);
};

/**
 * @returns {flatbuffers.Long}
 */
dataSize():flatbuffers.Long {
  return this.bb!.readUint64(this.bb_pos + 16);
};

/**
 * @returns {flatbuffers.Long}
 */
metadataOffset():flatbuffers.Long {
  return this.bb!.readUint64(this.bb_pos + 24);
};

/**
 * @returns {flatbuffers.Long}
 */
metadataSize():flatbuffers.Long {
  return this.bb!.readUint64(this.bb_pos + 32);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} segment_index
 * @param {flatbuffers.Long} data_offset
 * @param {flatbuffers.Long} data_size
 * @param {flatbuffers.Long} metadata_offset
 * @param {flatbuffers.Long} metadata_size
 * @returns {flatbuffers.Offset}
 */
static createPlasmaObjectSpec(builder:flatbuffers.Builder, segment_index: number, data_offset: flatbuffers.Long, data_size: flatbuffers.Long, metadata_offset: flatbuffers.Long, metadata_size: flatbuffers.Long):flatbuffers.Offset {
  builder.prep(8, 40);
  builder.writeInt64(metadata_size);
  builder.writeInt64(metadata_offset);
  builder.writeInt64(data_size);
  builder.writeInt64(data_offset);
  builder.pad(4);
  builder.writeInt32(segment_index);
  return builder.offset();
};

}
/**
 * @constructor
 */
export class PlasmaCreateRequest {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaCreateRequest}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaCreateRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaCreateRequest=} obj
 * @returns {PlasmaCreateRequest}
 */
static getRootAsPlasmaCreateRequest(bb:flatbuffers.ByteBuffer, obj?:PlasmaCreateRequest):PlasmaCreateRequest {
  return (obj || new PlasmaCreateRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
objectId():string|null
objectId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
dataSize():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
metadataSize():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaCreateRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
static addObjectId(builder:flatbuffers.Builder, objectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} dataSize
 */
static addDataSize(builder:flatbuffers.Builder, dataSize:flatbuffers.Long) {
  builder.addFieldInt64(1, dataSize, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} metadataSize
 */
static addMetadataSize(builder:flatbuffers.Builder, metadataSize:flatbuffers.Long) {
  builder.addFieldInt64(2, metadataSize, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaCreateRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaCreateReply {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaCreateReply}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaCreateReply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaCreateReply=} obj
 * @returns {PlasmaCreateReply}
 */
static getRootAsPlasmaCreateReply(bb:flatbuffers.ByteBuffer, obj?:PlasmaCreateReply):PlasmaCreateReply {
  return (obj || new PlasmaCreateReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
objectId():string|null
objectId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {PlasmaObjectSpec=} obj
 * @returns {PlasmaObjectSpec|null}
 */
plasmaObject(obj?:PlasmaObjectSpec):PlasmaObjectSpec|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new PlasmaObjectSpec).__init(this.bb_pos + offset, this.bb!) : null;
};

/**
 * @returns {PlasmaError}
 */
error():PlasmaError {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? /** @type {PlasmaError} */ (this.bb!.readInt32(this.bb_pos + offset)) : PlasmaError.OK;
};

/**
 * @returns {number}
 */
storeFd():number {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {flatbuffers.Long}
 */
mmapSize():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaCreateReply(builder:flatbuffers.Builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
static addObjectId(builder:flatbuffers.Builder, objectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} plasmaObjectOffset
 */
static addPlasmaObject(builder:flatbuffers.Builder, plasmaObjectOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, plasmaObjectOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {PlasmaError} error
 */
static addError(builder:flatbuffers.Builder, error:PlasmaError) {
  builder.addFieldInt32(2, error, PlasmaError.OK);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} storeFd
 */
static addStoreFd(builder:flatbuffers.Builder, storeFd:number) {
  builder.addFieldInt32(3, storeFd, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} mmapSize
 */
static addMmapSize(builder:flatbuffers.Builder, mmapSize:flatbuffers.Long) {
  builder.addFieldInt64(4, mmapSize, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaCreateReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaAbortRequest {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaAbortRequest}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaAbortRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaAbortRequest=} obj
 * @returns {PlasmaAbortRequest}
 */
static getRootAsPlasmaAbortRequest(bb:flatbuffers.ByteBuffer, obj?:PlasmaAbortRequest):PlasmaAbortRequest {
  return (obj || new PlasmaAbortRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
objectId():string|null
objectId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaAbortRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
static addObjectId(builder:flatbuffers.Builder, objectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaAbortRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaAbortReply {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaAbortReply}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaAbortReply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaAbortReply=} obj
 * @returns {PlasmaAbortReply}
 */
static getRootAsPlasmaAbortReply(bb:flatbuffers.ByteBuffer, obj?:PlasmaAbortReply):PlasmaAbortReply {
  return (obj || new PlasmaAbortReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
objectId():string|null
objectId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaAbortReply(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
static addObjectId(builder:flatbuffers.Builder, objectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaAbortReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaSealRequest {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaSealRequest}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaSealRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaSealRequest=} obj
 * @returns {PlasmaSealRequest}
 */
static getRootAsPlasmaSealRequest(bb:flatbuffers.ByteBuffer, obj?:PlasmaSealRequest):PlasmaSealRequest {
  return (obj || new PlasmaSealRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
objectId():string|null
objectId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
digest():string|null
digest(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
digest(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaSealRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
static addObjectId(builder:flatbuffers.Builder, objectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} digestOffset
 */
static addDigest(builder:flatbuffers.Builder, digestOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, digestOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaSealRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaSealReply {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaSealReply}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaSealReply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaSealReply=} obj
 * @returns {PlasmaSealReply}
 */
static getRootAsPlasmaSealReply(bb:flatbuffers.ByteBuffer, obj?:PlasmaSealReply):PlasmaSealReply {
  return (obj || new PlasmaSealReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
objectId():string|null
objectId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {PlasmaError}
 */
error():PlasmaError {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? /** @type {PlasmaError} */ (this.bb!.readInt32(this.bb_pos + offset)) : PlasmaError.OK;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaSealReply(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
static addObjectId(builder:flatbuffers.Builder, objectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {PlasmaError} error
 */
static addError(builder:flatbuffers.Builder, error:PlasmaError) {
  builder.addFieldInt32(1, error, PlasmaError.OK);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaSealReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaGetRequest {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaGetRequest}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaGetRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaGetRequest=} obj
 * @returns {PlasmaGetRequest}
 */
static getRootAsPlasmaGetRequest(bb:flatbuffers.ByteBuffer, obj?:PlasmaGetRequest):PlasmaGetRequest {
  return (obj || new PlasmaGetRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
objectIds(index: number):string
objectIds(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
objectIds(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
objectIdsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {flatbuffers.Long}
 */
timeoutMs():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaGetRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdsOffset
 */
static addObjectIds(builder:flatbuffers.Builder, objectIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
static createObjectIdsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
static startObjectIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timeoutMs
 */
static addTimeoutMs(builder:flatbuffers.Builder, timeoutMs:flatbuffers.Long) {
  builder.addFieldInt64(1, timeoutMs, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaGetRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaGetReply {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaGetReply}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaGetReply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaGetReply=} obj
 * @returns {PlasmaGetReply}
 */
static getRootAsPlasmaGetReply(bb:flatbuffers.ByteBuffer, obj?:PlasmaGetReply):PlasmaGetReply {
  return (obj || new PlasmaGetReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
objectIds(index: number):string
objectIds(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
objectIds(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
objectIdsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {PlasmaObjectSpec=} obj
 * @returns {PlasmaObjectSpec}
 */
plasmaObjects(index: number, obj?:PlasmaObjectSpec):PlasmaObjectSpec|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new PlasmaObjectSpec).__init(this.bb!.__vector(this.bb_pos + offset) + index * 40, this.bb!) : null;
};

/**
 * @returns {number}
 */
plasmaObjectsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @returns {number}
 */
storeFds(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
};

/**
 * @returns {number}
 */
storeFdsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Int32Array}
 */
storeFdsArray():Int32Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Int32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {number} index
 * @returns {flatbuffers.Long}
 */
mmapSizes(index: number):flatbuffers.Long|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt64(this.bb!.__vector(this.bb_pos + offset) + index * 8) : this.bb!.createLong(0, 0);
};

/**
 * @returns {number}
 */
mmapSizesLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaGetReply(builder:flatbuffers.Builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdsOffset
 */
static addObjectIds(builder:flatbuffers.Builder, objectIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
static createObjectIdsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
static startObjectIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} plasmaObjectsOffset
 */
static addPlasmaObjects(builder:flatbuffers.Builder, plasmaObjectsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, plasmaObjectsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
static startPlasmaObjectsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(40, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} storeFdsOffset
 */
static addStoreFds(builder:flatbuffers.Builder, storeFdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, storeFdsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
static createStoreFdsVector(builder:flatbuffers.Builder, data:number[] | Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
static startStoreFdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} mmapSizesOffset
 */
static addMmapSizes(builder:flatbuffers.Builder, mmapSizesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, mmapSizesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Long>} data
 * @returns {flatbuffers.Offset}
 */
static createMmapSizesVector(builder:flatbuffers.Builder, data:flatbuffers.Long[]):flatbuffers.Offset {
  builder.startVector(8, data.length, 8);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
static startMmapSizesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaGetReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaReleaseRequest {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaReleaseRequest}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaReleaseRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaReleaseRequest=} obj
 * @returns {PlasmaReleaseRequest}
 */
static getRootAsPlasmaReleaseRequest(bb:flatbuffers.ByteBuffer, obj?:PlasmaReleaseRequest):PlasmaReleaseRequest {
  return (obj || new PlasmaReleaseRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
objectId():string|null
objectId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaReleaseRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
static addObjectId(builder:flatbuffers.Builder, objectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaReleaseRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaReleaseReply {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaReleaseReply}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaReleaseReply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaReleaseReply=} obj
 * @returns {PlasmaReleaseReply}
 */
static getRootAsPlasmaReleaseReply(bb:flatbuffers.ByteBuffer, obj?:PlasmaReleaseReply):PlasmaReleaseReply {
  return (obj || new PlasmaReleaseReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
objectId():string|null
objectId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {PlasmaError}
 */
error():PlasmaError {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? /** @type {PlasmaError} */ (this.bb!.readInt32(this.bb_pos + offset)) : PlasmaError.OK;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaReleaseReply(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
static addObjectId(builder:flatbuffers.Builder, objectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {PlasmaError} error
 */
static addError(builder:flatbuffers.Builder, error:PlasmaError) {
  builder.addFieldInt32(1, error, PlasmaError.OK);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaReleaseReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaDeleteRequest {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaDeleteRequest}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaDeleteRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaDeleteRequest=} obj
 * @returns {PlasmaDeleteRequest}
 */
static getRootAsPlasmaDeleteRequest(bb:flatbuffers.ByteBuffer, obj?:PlasmaDeleteRequest):PlasmaDeleteRequest {
  return (obj || new PlasmaDeleteRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
objectId():string|null
objectId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaDeleteRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
static addObjectId(builder:flatbuffers.Builder, objectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaDeleteRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaDeleteReply {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaDeleteReply}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaDeleteReply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaDeleteReply=} obj
 * @returns {PlasmaDeleteReply}
 */
static getRootAsPlasmaDeleteReply(bb:flatbuffers.ByteBuffer, obj?:PlasmaDeleteReply):PlasmaDeleteReply {
  return (obj || new PlasmaDeleteReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
objectId():string|null
objectId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {PlasmaError}
 */
error():PlasmaError {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? /** @type {PlasmaError} */ (this.bb!.readInt32(this.bb_pos + offset)) : PlasmaError.OK;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaDeleteReply(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
static addObjectId(builder:flatbuffers.Builder, objectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {PlasmaError} error
 */
static addError(builder:flatbuffers.Builder, error:PlasmaError) {
  builder.addFieldInt32(1, error, PlasmaError.OK);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaDeleteReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaStatusRequest {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaStatusRequest}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaStatusRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaStatusRequest=} obj
 * @returns {PlasmaStatusRequest}
 */
static getRootAsPlasmaStatusRequest(bb:flatbuffers.ByteBuffer, obj?:PlasmaStatusRequest):PlasmaStatusRequest {
  return (obj || new PlasmaStatusRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
objectIds(index: number):string
objectIds(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
objectIds(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
objectIdsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaStatusRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdsOffset
 */
static addObjectIds(builder:flatbuffers.Builder, objectIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
static createObjectIdsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
static startObjectIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaStatusRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaStatusReply {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaStatusReply}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaStatusReply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaStatusReply=} obj
 * @returns {PlasmaStatusReply}
 */
static getRootAsPlasmaStatusReply(bb:flatbuffers.ByteBuffer, obj?:PlasmaStatusReply):PlasmaStatusReply {
  return (obj || new PlasmaStatusReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
objectIds(index: number):string
objectIds(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
objectIds(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
objectIdsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @returns {ObjectStatus}
 */
status(index: number):ObjectStatus|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? /** @type {ObjectStatus} */ (this.bb!.readInt32(this.bb!.__vector(this.bb_pos + offset) + index * 4)) : /** @type {ObjectStatus} */ (0);
};

/**
 * @returns {number}
 */
statusLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Int32Array}
 */
statusArray():Int32Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Int32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaStatusReply(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdsOffset
 */
static addObjectIds(builder:flatbuffers.Builder, objectIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
static createObjectIdsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
static startObjectIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} statusOffset
 */
static addStatus(builder:flatbuffers.Builder, statusOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, statusOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<ObjectStatus>} data
 * @returns {flatbuffers.Offset}
 */
static createStatusVector(builder:flatbuffers.Builder, data:ObjectStatus[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
static startStatusVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaStatusReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaContainsRequest {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaContainsRequest}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaContainsRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaContainsRequest=} obj
 * @returns {PlasmaContainsRequest}
 */
static getRootAsPlasmaContainsRequest(bb:flatbuffers.ByteBuffer, obj?:PlasmaContainsRequest):PlasmaContainsRequest {
  return (obj || new PlasmaContainsRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
objectId():string|null
objectId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaContainsRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
static addObjectId(builder:flatbuffers.Builder, objectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaContainsRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaContainsReply {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaContainsReply}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaContainsReply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaContainsReply=} obj
 * @returns {PlasmaContainsReply}
 */
static getRootAsPlasmaContainsReply(bb:flatbuffers.ByteBuffer, obj?:PlasmaContainsReply):PlasmaContainsReply {
  return (obj || new PlasmaContainsReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
objectId():string|null
objectId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
hasObject():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaContainsReply(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
static addObjectId(builder:flatbuffers.Builder, objectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} hasObject
 */
static addHasObject(builder:flatbuffers.Builder, hasObject:number) {
  builder.addFieldInt32(1, hasObject, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaContainsReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaConnectRequest {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaConnectRequest}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaConnectRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaConnectRequest=} obj
 * @returns {PlasmaConnectRequest}
 */
static getRootAsPlasmaConnectRequest(bb:flatbuffers.ByteBuffer, obj?:PlasmaConnectRequest):PlasmaConnectRequest {
  return (obj || new PlasmaConnectRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaConnectRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaConnectRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaConnectReply {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaConnectReply}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaConnectReply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaConnectReply=} obj
 * @returns {PlasmaConnectReply}
 */
static getRootAsPlasmaConnectReply(bb:flatbuffers.ByteBuffer, obj?:PlasmaConnectReply):PlasmaConnectReply {
  return (obj || new PlasmaConnectReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
memoryCapacity():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaConnectReply(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} memoryCapacity
 */
static addMemoryCapacity(builder:flatbuffers.Builder, memoryCapacity:flatbuffers.Long) {
  builder.addFieldInt64(0, memoryCapacity, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaConnectReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaEvictRequest {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaEvictRequest}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaEvictRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaEvictRequest=} obj
 * @returns {PlasmaEvictRequest}
 */
static getRootAsPlasmaEvictRequest(bb:flatbuffers.ByteBuffer, obj?:PlasmaEvictRequest):PlasmaEvictRequest {
  return (obj || new PlasmaEvictRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
numBytes():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaEvictRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} numBytes
 */
static addNumBytes(builder:flatbuffers.Builder, numBytes:flatbuffers.Long) {
  builder.addFieldInt64(0, numBytes, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaEvictRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaEvictReply {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaEvictReply}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaEvictReply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaEvictReply=} obj
 * @returns {PlasmaEvictReply}
 */
static getRootAsPlasmaEvictReply(bb:flatbuffers.ByteBuffer, obj?:PlasmaEvictReply):PlasmaEvictReply {
  return (obj || new PlasmaEvictReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
numBytes():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaEvictReply(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} numBytes
 */
static addNumBytes(builder:flatbuffers.Builder, numBytes:flatbuffers.Long) {
  builder.addFieldInt64(0, numBytes, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaEvictReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaFetchRequest {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaFetchRequest}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaFetchRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaFetchRequest=} obj
 * @returns {PlasmaFetchRequest}
 */
static getRootAsPlasmaFetchRequest(bb:flatbuffers.ByteBuffer, obj?:PlasmaFetchRequest):PlasmaFetchRequest {
  return (obj || new PlasmaFetchRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
objectIds(index: number):string
objectIds(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
objectIds(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
objectIdsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaFetchRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdsOffset
 */
static addObjectIds(builder:flatbuffers.Builder, objectIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
static createObjectIdsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
static startObjectIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaFetchRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class ObjectRequestSpec {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ObjectRequestSpec}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ObjectRequestSpec {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ObjectRequestSpec=} obj
 * @returns {ObjectRequestSpec}
 */
static getRootAsObjectRequestSpec(bb:flatbuffers.ByteBuffer, obj?:ObjectRequestSpec):ObjectRequestSpec {
  return (obj || new ObjectRequestSpec).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
objectId():string|null
objectId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
type():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startObjectRequestSpec(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
static addObjectId(builder:flatbuffers.Builder, objectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} type
 */
static addType(builder:flatbuffers.Builder, type:number) {
  builder.addFieldInt32(1, type, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endObjectRequestSpec(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaWaitRequest {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaWaitRequest}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaWaitRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaWaitRequest=} obj
 * @returns {PlasmaWaitRequest}
 */
static getRootAsPlasmaWaitRequest(bb:flatbuffers.ByteBuffer, obj?:PlasmaWaitRequest):PlasmaWaitRequest {
  return (obj || new PlasmaWaitRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {ObjectRequestSpec=} obj
 * @returns {ObjectRequestSpec}
 */
objectRequests(index: number, obj?:ObjectRequestSpec):ObjectRequestSpec|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ObjectRequestSpec).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns {number}
 */
objectRequestsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
numReadyObjects():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {flatbuffers.Long}
 */
timeout():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaWaitRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectRequestsOffset
 */
static addObjectRequests(builder:flatbuffers.Builder, objectRequestsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectRequestsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
static createObjectRequestsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
static startObjectRequestsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numReadyObjects
 */
static addNumReadyObjects(builder:flatbuffers.Builder, numReadyObjects:number) {
  builder.addFieldInt32(1, numReadyObjects, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timeout
 */
static addTimeout(builder:flatbuffers.Builder, timeout:flatbuffers.Long) {
  builder.addFieldInt64(2, timeout, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaWaitRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class ObjectReply {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ObjectReply}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ObjectReply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ObjectReply=} obj
 * @returns {ObjectReply}
 */
static getRootAsObjectReply(bb:flatbuffers.ByteBuffer, obj?:ObjectReply):ObjectReply {
  return (obj || new ObjectReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
objectId():string|null
objectId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
status():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startObjectReply(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
static addObjectId(builder:flatbuffers.Builder, objectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} status
 */
static addStatus(builder:flatbuffers.Builder, status:number) {
  builder.addFieldInt32(1, status, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endObjectReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaWaitReply {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaWaitReply}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaWaitReply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaWaitReply=} obj
 * @returns {PlasmaWaitReply}
 */
static getRootAsPlasmaWaitReply(bb:flatbuffers.ByteBuffer, obj?:PlasmaWaitReply):PlasmaWaitReply {
  return (obj || new PlasmaWaitReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {ObjectReply=} obj
 * @returns {ObjectReply}
 */
objectRequests(index: number, obj?:ObjectReply):ObjectReply|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ObjectReply).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns {number}
 */
objectRequestsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
numReadyObjects():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaWaitReply(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectRequestsOffset
 */
static addObjectRequests(builder:flatbuffers.Builder, objectRequestsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectRequestsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
static createObjectRequestsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
static startObjectRequestsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numReadyObjects
 */
static addNumReadyObjects(builder:flatbuffers.Builder, numReadyObjects:number) {
  builder.addFieldInt32(1, numReadyObjects, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaWaitReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaSubscribeRequest {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaSubscribeRequest}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaSubscribeRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaSubscribeRequest=} obj
 * @returns {PlasmaSubscribeRequest}
 */
static getRootAsPlasmaSubscribeRequest(bb:flatbuffers.ByteBuffer, obj?:PlasmaSubscribeRequest):PlasmaSubscribeRequest {
  return (obj || new PlasmaSubscribeRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaSubscribeRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaSubscribeRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaDataRequest {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaDataRequest}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaDataRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaDataRequest=} obj
 * @returns {PlasmaDataRequest}
 */
static getRootAsPlasmaDataRequest(bb:flatbuffers.ByteBuffer, obj?:PlasmaDataRequest):PlasmaDataRequest {
  return (obj || new PlasmaDataRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
objectId():string|null
objectId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
address():string|null
address(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
address(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
port():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaDataRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
static addObjectId(builder:flatbuffers.Builder, objectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} addressOffset
 */
static addAddress(builder:flatbuffers.Builder, addressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, addressOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} port
 */
static addPort(builder:flatbuffers.Builder, port:number) {
  builder.addFieldInt32(2, port, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaDataRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
/**
 * @constructor
 */
export class PlasmaDataReply {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  bb: flatbuffers.ByteBuffer|null = null;

  /**
   * @type {number}
   */
  bb_pos:number = 0;
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaDataReply}
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlasmaDataReply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaDataReply=} obj
 * @returns {PlasmaDataReply}
 */
static getRootAsPlasmaDataReply(bb:flatbuffers.ByteBuffer, obj?:PlasmaDataReply):PlasmaDataReply {
  return (obj || new PlasmaDataReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
objectId():string|null
objectId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
objectId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
objectSize():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
metadataSize():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
static startPlasmaDataReply(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
static addObjectId(builder:flatbuffers.Builder, objectIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} objectSize
 */
static addObjectSize(builder:flatbuffers.Builder, objectSize:flatbuffers.Long) {
  builder.addFieldInt64(1, objectSize, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} metadataSize
 */
static addMetadataSize(builder:flatbuffers.Builder, metadataSize:flatbuffers.Long) {
  builder.addFieldInt64(2, metadataSize, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
static endPlasmaDataReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
