// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @enum
 */
var MessageType = {
  PlasmaCreateRequest: 1,
  PlasmaCreateReply: 2,
  PlasmaAbortRequest: 3,
  PlasmaAbortReply: 4,
  PlasmaSealRequest: 5,
  PlasmaSealReply: 6,
  PlasmaGetRequest: 7,
  PlasmaGetReply: 8,
  PlasmaReleaseRequest: 9,
  PlasmaReleaseReply: 10,
  PlasmaDeleteRequest: 11,
  PlasmaDeleteReply: 12,
  PlasmaStatusRequest: 13,
  PlasmaStatusReply: 14,
  PlasmaContainsRequest: 15,
  PlasmaContainsReply: 16,
  PlasmaConnectRequest: 17,
  PlasmaConnectReply: 18,
  PlasmaEvictRequest: 19,
  PlasmaEvictReply: 20,
  PlasmaFetchRequest: 21,
  PlasmaWaitRequest: 22,
  PlasmaWaitReply: 23,
  PlasmaSubscribeRequest: 24,
  PlasmaUnsubscribeRequest: 25,
  PlasmaDataRequest: 26,
  PlasmaDataReply: 27,
  PlasmaNotification: 28
};

/**
 * @enum
 */
var PlasmaError = {
  OK: 0,
  ObjectExists: 1,
  ObjectNonexistent: 2,
  OutOfMemory: 3,
  ObjectNotSealed: 4,
  ObjectInUse: 5
};

/**
 * @enum
 */
var ObjectStatus = {
  Local: 1,
  Remote: 2,
  Nonexistent: 3,
  Transfer: 4
};

/**
 * @constructor
 */
function PlasmaObjectSpec() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaObjectSpec}
 */
PlasmaObjectSpec.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
PlasmaObjectSpec.prototype.segmentIndex = function() {
  return this.bb.readInt32(this.bb_pos);
};

/**
 * @returns {flatbuffers.Long}
 */
PlasmaObjectSpec.prototype.dataOffset = function() {
  return this.bb.readUint64(this.bb_pos + 8);
};

/**
 * @returns {flatbuffers.Long}
 */
PlasmaObjectSpec.prototype.dataSize = function() {
  return this.bb.readUint64(this.bb_pos + 16);
};

/**
 * @returns {flatbuffers.Long}
 */
PlasmaObjectSpec.prototype.metadataOffset = function() {
  return this.bb.readUint64(this.bb_pos + 24);
};

/**
 * @returns {flatbuffers.Long}
 */
PlasmaObjectSpec.prototype.metadataSize = function() {
  return this.bb.readUint64(this.bb_pos + 32);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} segment_index
 * @param {flatbuffers.Long} data_offset
 * @param {flatbuffers.Long} data_size
 * @param {flatbuffers.Long} metadata_offset
 * @param {flatbuffers.Long} metadata_size
 * @returns {flatbuffers.Offset}
 */
PlasmaObjectSpec.createPlasmaObjectSpec = function(builder, segment_index, data_offset, data_size, metadata_offset, metadata_size) {
  builder.prep(8, 40);
  builder.writeInt64(metadata_size);
  builder.writeInt64(metadata_offset);
  builder.writeInt64(data_size);
  builder.writeInt64(data_offset);
  builder.pad(4);
  builder.writeInt32(segment_index);
  return builder.offset();
};

/**
 * @constructor
 */
function PlasmaCreateRequest() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaCreateRequest}
 */
PlasmaCreateRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaCreateRequest=} obj
 * @returns {PlasmaCreateRequest}
 */
PlasmaCreateRequest.getRootAsPlasmaCreateRequest = function(bb, obj) {
  return (obj || new PlasmaCreateRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
PlasmaCreateRequest.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
PlasmaCreateRequest.prototype.dataSize = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
PlasmaCreateRequest.prototype.metadataSize = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaCreateRequest.startPlasmaCreateRequest = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
PlasmaCreateRequest.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} dataSize
 */
PlasmaCreateRequest.addDataSize = function(builder, dataSize) {
  builder.addFieldInt64(1, dataSize, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} metadataSize
 */
PlasmaCreateRequest.addMetadataSize = function(builder, metadataSize) {
  builder.addFieldInt64(2, metadataSize, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaCreateRequest.endPlasmaCreateRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaCreateReply() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaCreateReply}
 */
PlasmaCreateReply.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaCreateReply=} obj
 * @returns {PlasmaCreateReply}
 */
PlasmaCreateReply.getRootAsPlasmaCreateReply = function(bb, obj) {
  return (obj || new PlasmaCreateReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
PlasmaCreateReply.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {PlasmaObjectSpec=} obj
 * @returns {PlasmaObjectSpec|null}
 */
PlasmaCreateReply.prototype.plasmaObject = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new PlasmaObjectSpec).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {PlasmaError}
 */
PlasmaCreateReply.prototype.error = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {PlasmaError} */ (this.bb.readInt32(this.bb_pos + offset)) : PlasmaError.OK;
};

/**
 * @returns {number}
 */
PlasmaCreateReply.prototype.storeFd = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {flatbuffers.Long}
 */
PlasmaCreateReply.prototype.mmapSize = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaCreateReply.startPlasmaCreateReply = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
PlasmaCreateReply.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} plasmaObjectOffset
 */
PlasmaCreateReply.addPlasmaObject = function(builder, plasmaObjectOffset) {
  builder.addFieldStruct(1, plasmaObjectOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {PlasmaError} error
 */
PlasmaCreateReply.addError = function(builder, error) {
  builder.addFieldInt32(2, error, PlasmaError.OK);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} storeFd
 */
PlasmaCreateReply.addStoreFd = function(builder, storeFd) {
  builder.addFieldInt32(3, storeFd, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} mmapSize
 */
PlasmaCreateReply.addMmapSize = function(builder, mmapSize) {
  builder.addFieldInt64(4, mmapSize, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaCreateReply.endPlasmaCreateReply = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaAbortRequest() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaAbortRequest}
 */
PlasmaAbortRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaAbortRequest=} obj
 * @returns {PlasmaAbortRequest}
 */
PlasmaAbortRequest.getRootAsPlasmaAbortRequest = function(bb, obj) {
  return (obj || new PlasmaAbortRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
PlasmaAbortRequest.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaAbortRequest.startPlasmaAbortRequest = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
PlasmaAbortRequest.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaAbortRequest.endPlasmaAbortRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaAbortReply() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaAbortReply}
 */
PlasmaAbortReply.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaAbortReply=} obj
 * @returns {PlasmaAbortReply}
 */
PlasmaAbortReply.getRootAsPlasmaAbortReply = function(bb, obj) {
  return (obj || new PlasmaAbortReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
PlasmaAbortReply.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaAbortReply.startPlasmaAbortReply = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
PlasmaAbortReply.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaAbortReply.endPlasmaAbortReply = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaSealRequest() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaSealRequest}
 */
PlasmaSealRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaSealRequest=} obj
 * @returns {PlasmaSealRequest}
 */
PlasmaSealRequest.getRootAsPlasmaSealRequest = function(bb, obj) {
  return (obj || new PlasmaSealRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
PlasmaSealRequest.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
PlasmaSealRequest.prototype.digest = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaSealRequest.startPlasmaSealRequest = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
PlasmaSealRequest.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} digestOffset
 */
PlasmaSealRequest.addDigest = function(builder, digestOffset) {
  builder.addFieldOffset(1, digestOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaSealRequest.endPlasmaSealRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaSealReply() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaSealReply}
 */
PlasmaSealReply.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaSealReply=} obj
 * @returns {PlasmaSealReply}
 */
PlasmaSealReply.getRootAsPlasmaSealReply = function(bb, obj) {
  return (obj || new PlasmaSealReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
PlasmaSealReply.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {PlasmaError}
 */
PlasmaSealReply.prototype.error = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {PlasmaError} */ (this.bb.readInt32(this.bb_pos + offset)) : PlasmaError.OK;
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaSealReply.startPlasmaSealReply = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
PlasmaSealReply.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {PlasmaError} error
 */
PlasmaSealReply.addError = function(builder, error) {
  builder.addFieldInt32(1, error, PlasmaError.OK);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaSealReply.endPlasmaSealReply = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaGetRequest() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaGetRequest}
 */
PlasmaGetRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaGetRequest=} obj
 * @returns {PlasmaGetRequest}
 */
PlasmaGetRequest.getRootAsPlasmaGetRequest = function(bb, obj) {
  return (obj || new PlasmaGetRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
PlasmaGetRequest.prototype.objectIds = function(index, optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
PlasmaGetRequest.prototype.objectIdsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {flatbuffers.Long}
 */
PlasmaGetRequest.prototype.timeoutMs = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaGetRequest.startPlasmaGetRequest = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdsOffset
 */
PlasmaGetRequest.addObjectIds = function(builder, objectIdsOffset) {
  builder.addFieldOffset(0, objectIdsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
PlasmaGetRequest.createObjectIdsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
PlasmaGetRequest.startObjectIdsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timeoutMs
 */
PlasmaGetRequest.addTimeoutMs = function(builder, timeoutMs) {
  builder.addFieldInt64(1, timeoutMs, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaGetRequest.endPlasmaGetRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaGetReply() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaGetReply}
 */
PlasmaGetReply.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaGetReply=} obj
 * @returns {PlasmaGetReply}
 */
PlasmaGetReply.getRootAsPlasmaGetReply = function(bb, obj) {
  return (obj || new PlasmaGetReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
PlasmaGetReply.prototype.objectIds = function(index, optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
PlasmaGetReply.prototype.objectIdsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {PlasmaObjectSpec=} obj
 * @returns {PlasmaObjectSpec}
 */
PlasmaGetReply.prototype.plasmaObjects = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new PlasmaObjectSpec).__init(this.bb.__vector(this.bb_pos + offset) + index * 40, this.bb) : null;
};

/**
 * @returns {number}
 */
PlasmaGetReply.prototype.plasmaObjectsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @returns {number}
 */
PlasmaGetReply.prototype.storeFds = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt32(this.bb.__vector(this.bb_pos + offset) + index * 4) : 0;
};

/**
 * @returns {number}
 */
PlasmaGetReply.prototype.storeFdsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Int32Array}
 */
PlasmaGetReply.prototype.storeFdsArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? new Int32Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {number} index
 * @returns {flatbuffers.Long}
 */
PlasmaGetReply.prototype.mmapSizes = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt64(this.bb.__vector(this.bb_pos + offset) + index * 8) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
PlasmaGetReply.prototype.mmapSizesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaGetReply.startPlasmaGetReply = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdsOffset
 */
PlasmaGetReply.addObjectIds = function(builder, objectIdsOffset) {
  builder.addFieldOffset(0, objectIdsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
PlasmaGetReply.createObjectIdsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
PlasmaGetReply.startObjectIdsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} plasmaObjectsOffset
 */
PlasmaGetReply.addPlasmaObjects = function(builder, plasmaObjectsOffset) {
  builder.addFieldOffset(1, plasmaObjectsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
PlasmaGetReply.startPlasmaObjectsVector = function(builder, numElems) {
  builder.startVector(40, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} storeFdsOffset
 */
PlasmaGetReply.addStoreFds = function(builder, storeFdsOffset) {
  builder.addFieldOffset(2, storeFdsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
PlasmaGetReply.createStoreFdsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
PlasmaGetReply.startStoreFdsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} mmapSizesOffset
 */
PlasmaGetReply.addMmapSizes = function(builder, mmapSizesOffset) {
  builder.addFieldOffset(3, mmapSizesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Long>} data
 * @returns {flatbuffers.Offset}
 */
PlasmaGetReply.createMmapSizesVector = function(builder, data) {
  builder.startVector(8, data.length, 8);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
PlasmaGetReply.startMmapSizesVector = function(builder, numElems) {
  builder.startVector(8, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaGetReply.endPlasmaGetReply = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaReleaseRequest() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaReleaseRequest}
 */
PlasmaReleaseRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaReleaseRequest=} obj
 * @returns {PlasmaReleaseRequest}
 */
PlasmaReleaseRequest.getRootAsPlasmaReleaseRequest = function(bb, obj) {
  return (obj || new PlasmaReleaseRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
PlasmaReleaseRequest.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaReleaseRequest.startPlasmaReleaseRequest = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
PlasmaReleaseRequest.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaReleaseRequest.endPlasmaReleaseRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaReleaseReply() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaReleaseReply}
 */
PlasmaReleaseReply.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaReleaseReply=} obj
 * @returns {PlasmaReleaseReply}
 */
PlasmaReleaseReply.getRootAsPlasmaReleaseReply = function(bb, obj) {
  return (obj || new PlasmaReleaseReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
PlasmaReleaseReply.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {PlasmaError}
 */
PlasmaReleaseReply.prototype.error = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {PlasmaError} */ (this.bb.readInt32(this.bb_pos + offset)) : PlasmaError.OK;
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaReleaseReply.startPlasmaReleaseReply = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
PlasmaReleaseReply.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {PlasmaError} error
 */
PlasmaReleaseReply.addError = function(builder, error) {
  builder.addFieldInt32(1, error, PlasmaError.OK);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaReleaseReply.endPlasmaReleaseReply = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaDeleteRequest() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaDeleteRequest}
 */
PlasmaDeleteRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaDeleteRequest=} obj
 * @returns {PlasmaDeleteRequest}
 */
PlasmaDeleteRequest.getRootAsPlasmaDeleteRequest = function(bb, obj) {
  return (obj || new PlasmaDeleteRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
PlasmaDeleteRequest.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaDeleteRequest.startPlasmaDeleteRequest = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
PlasmaDeleteRequest.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaDeleteRequest.endPlasmaDeleteRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaDeleteReply() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaDeleteReply}
 */
PlasmaDeleteReply.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaDeleteReply=} obj
 * @returns {PlasmaDeleteReply}
 */
PlasmaDeleteReply.getRootAsPlasmaDeleteReply = function(bb, obj) {
  return (obj || new PlasmaDeleteReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
PlasmaDeleteReply.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {PlasmaError}
 */
PlasmaDeleteReply.prototype.error = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {PlasmaError} */ (this.bb.readInt32(this.bb_pos + offset)) : PlasmaError.OK;
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaDeleteReply.startPlasmaDeleteReply = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
PlasmaDeleteReply.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {PlasmaError} error
 */
PlasmaDeleteReply.addError = function(builder, error) {
  builder.addFieldInt32(1, error, PlasmaError.OK);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaDeleteReply.endPlasmaDeleteReply = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaStatusRequest() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaStatusRequest}
 */
PlasmaStatusRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaStatusRequest=} obj
 * @returns {PlasmaStatusRequest}
 */
PlasmaStatusRequest.getRootAsPlasmaStatusRequest = function(bb, obj) {
  return (obj || new PlasmaStatusRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
PlasmaStatusRequest.prototype.objectIds = function(index, optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
PlasmaStatusRequest.prototype.objectIdsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaStatusRequest.startPlasmaStatusRequest = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdsOffset
 */
PlasmaStatusRequest.addObjectIds = function(builder, objectIdsOffset) {
  builder.addFieldOffset(0, objectIdsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
PlasmaStatusRequest.createObjectIdsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
PlasmaStatusRequest.startObjectIdsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaStatusRequest.endPlasmaStatusRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaStatusReply() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaStatusReply}
 */
PlasmaStatusReply.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaStatusReply=} obj
 * @returns {PlasmaStatusReply}
 */
PlasmaStatusReply.getRootAsPlasmaStatusReply = function(bb, obj) {
  return (obj || new PlasmaStatusReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
PlasmaStatusReply.prototype.objectIds = function(index, optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
PlasmaStatusReply.prototype.objectIdsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @returns {ObjectStatus}
 */
PlasmaStatusReply.prototype.status = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {ObjectStatus} */ (this.bb.readInt32(this.bb.__vector(this.bb_pos + offset) + index * 4)) : /** @type {ObjectStatus} */ (0);
};

/**
 * @returns {number}
 */
PlasmaStatusReply.prototype.statusLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Int32Array}
 */
PlasmaStatusReply.prototype.statusArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? new Int32Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaStatusReply.startPlasmaStatusReply = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdsOffset
 */
PlasmaStatusReply.addObjectIds = function(builder, objectIdsOffset) {
  builder.addFieldOffset(0, objectIdsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
PlasmaStatusReply.createObjectIdsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
PlasmaStatusReply.startObjectIdsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} statusOffset
 */
PlasmaStatusReply.addStatus = function(builder, statusOffset) {
  builder.addFieldOffset(1, statusOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<ObjectStatus>} data
 * @returns {flatbuffers.Offset}
 */
PlasmaStatusReply.createStatusVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
PlasmaStatusReply.startStatusVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaStatusReply.endPlasmaStatusReply = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaContainsRequest() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaContainsRequest}
 */
PlasmaContainsRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaContainsRequest=} obj
 * @returns {PlasmaContainsRequest}
 */
PlasmaContainsRequest.getRootAsPlasmaContainsRequest = function(bb, obj) {
  return (obj || new PlasmaContainsRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
PlasmaContainsRequest.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaContainsRequest.startPlasmaContainsRequest = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
PlasmaContainsRequest.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaContainsRequest.endPlasmaContainsRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaContainsReply() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaContainsReply}
 */
PlasmaContainsReply.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaContainsReply=} obj
 * @returns {PlasmaContainsReply}
 */
PlasmaContainsReply.getRootAsPlasmaContainsReply = function(bb, obj) {
  return (obj || new PlasmaContainsReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
PlasmaContainsReply.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
PlasmaContainsReply.prototype.hasObject = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaContainsReply.startPlasmaContainsReply = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
PlasmaContainsReply.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} hasObject
 */
PlasmaContainsReply.addHasObject = function(builder, hasObject) {
  builder.addFieldInt32(1, hasObject, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaContainsReply.endPlasmaContainsReply = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaConnectRequest() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaConnectRequest}
 */
PlasmaConnectRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaConnectRequest=} obj
 * @returns {PlasmaConnectRequest}
 */
PlasmaConnectRequest.getRootAsPlasmaConnectRequest = function(bb, obj) {
  return (obj || new PlasmaConnectRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaConnectRequest.startPlasmaConnectRequest = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaConnectRequest.endPlasmaConnectRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaConnectReply() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaConnectReply}
 */
PlasmaConnectReply.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaConnectReply=} obj
 * @returns {PlasmaConnectReply}
 */
PlasmaConnectReply.getRootAsPlasmaConnectReply = function(bb, obj) {
  return (obj || new PlasmaConnectReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
PlasmaConnectReply.prototype.memoryCapacity = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaConnectReply.startPlasmaConnectReply = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} memoryCapacity
 */
PlasmaConnectReply.addMemoryCapacity = function(builder, memoryCapacity) {
  builder.addFieldInt64(0, memoryCapacity, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaConnectReply.endPlasmaConnectReply = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaEvictRequest() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaEvictRequest}
 */
PlasmaEvictRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaEvictRequest=} obj
 * @returns {PlasmaEvictRequest}
 */
PlasmaEvictRequest.getRootAsPlasmaEvictRequest = function(bb, obj) {
  return (obj || new PlasmaEvictRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
PlasmaEvictRequest.prototype.numBytes = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaEvictRequest.startPlasmaEvictRequest = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} numBytes
 */
PlasmaEvictRequest.addNumBytes = function(builder, numBytes) {
  builder.addFieldInt64(0, numBytes, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaEvictRequest.endPlasmaEvictRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaEvictReply() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaEvictReply}
 */
PlasmaEvictReply.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaEvictReply=} obj
 * @returns {PlasmaEvictReply}
 */
PlasmaEvictReply.getRootAsPlasmaEvictReply = function(bb, obj) {
  return (obj || new PlasmaEvictReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
PlasmaEvictReply.prototype.numBytes = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaEvictReply.startPlasmaEvictReply = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} numBytes
 */
PlasmaEvictReply.addNumBytes = function(builder, numBytes) {
  builder.addFieldInt64(0, numBytes, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaEvictReply.endPlasmaEvictReply = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaFetchRequest() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaFetchRequest}
 */
PlasmaFetchRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaFetchRequest=} obj
 * @returns {PlasmaFetchRequest}
 */
PlasmaFetchRequest.getRootAsPlasmaFetchRequest = function(bb, obj) {
  return (obj || new PlasmaFetchRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
PlasmaFetchRequest.prototype.objectIds = function(index, optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
PlasmaFetchRequest.prototype.objectIdsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaFetchRequest.startPlasmaFetchRequest = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdsOffset
 */
PlasmaFetchRequest.addObjectIds = function(builder, objectIdsOffset) {
  builder.addFieldOffset(0, objectIdsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
PlasmaFetchRequest.createObjectIdsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
PlasmaFetchRequest.startObjectIdsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaFetchRequest.endPlasmaFetchRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function ObjectRequestSpec() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ObjectRequestSpec}
 */
ObjectRequestSpec.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ObjectRequestSpec=} obj
 * @returns {ObjectRequestSpec}
 */
ObjectRequestSpec.getRootAsObjectRequestSpec = function(bb, obj) {
  return (obj || new ObjectRequestSpec).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ObjectRequestSpec.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
ObjectRequestSpec.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ObjectRequestSpec.startObjectRequestSpec = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
ObjectRequestSpec.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} type
 */
ObjectRequestSpec.addType = function(builder, type) {
  builder.addFieldInt32(1, type, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ObjectRequestSpec.endObjectRequestSpec = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaWaitRequest() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaWaitRequest}
 */
PlasmaWaitRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaWaitRequest=} obj
 * @returns {PlasmaWaitRequest}
 */
PlasmaWaitRequest.getRootAsPlasmaWaitRequest = function(bb, obj) {
  return (obj || new PlasmaWaitRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {ObjectRequestSpec=} obj
 * @returns {ObjectRequestSpec}
 */
PlasmaWaitRequest.prototype.objectRequests = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new ObjectRequestSpec).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
PlasmaWaitRequest.prototype.objectRequestsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
PlasmaWaitRequest.prototype.numReadyObjects = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {flatbuffers.Long}
 */
PlasmaWaitRequest.prototype.timeout = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaWaitRequest.startPlasmaWaitRequest = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectRequestsOffset
 */
PlasmaWaitRequest.addObjectRequests = function(builder, objectRequestsOffset) {
  builder.addFieldOffset(0, objectRequestsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
PlasmaWaitRequest.createObjectRequestsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
PlasmaWaitRequest.startObjectRequestsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numReadyObjects
 */
PlasmaWaitRequest.addNumReadyObjects = function(builder, numReadyObjects) {
  builder.addFieldInt32(1, numReadyObjects, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timeout
 */
PlasmaWaitRequest.addTimeout = function(builder, timeout) {
  builder.addFieldInt64(2, timeout, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaWaitRequest.endPlasmaWaitRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function ObjectReply() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {ObjectReply}
 */
ObjectReply.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {ObjectReply=} obj
 * @returns {ObjectReply}
 */
ObjectReply.getRootAsObjectReply = function(bb, obj) {
  return (obj || new ObjectReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
ObjectReply.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
ObjectReply.prototype.status = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
ObjectReply.startObjectReply = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
ObjectReply.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} status
 */
ObjectReply.addStatus = function(builder, status) {
  builder.addFieldInt32(1, status, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
ObjectReply.endObjectReply = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaWaitReply() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaWaitReply}
 */
PlasmaWaitReply.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaWaitReply=} obj
 * @returns {PlasmaWaitReply}
 */
PlasmaWaitReply.getRootAsPlasmaWaitReply = function(bb, obj) {
  return (obj || new PlasmaWaitReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {ObjectReply=} obj
 * @returns {ObjectReply}
 */
PlasmaWaitReply.prototype.objectRequests = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new ObjectReply).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
PlasmaWaitReply.prototype.objectRequestsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
PlasmaWaitReply.prototype.numReadyObjects = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaWaitReply.startPlasmaWaitReply = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectRequestsOffset
 */
PlasmaWaitReply.addObjectRequests = function(builder, objectRequestsOffset) {
  builder.addFieldOffset(0, objectRequestsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
PlasmaWaitReply.createObjectRequestsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
PlasmaWaitReply.startObjectRequestsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numReadyObjects
 */
PlasmaWaitReply.addNumReadyObjects = function(builder, numReadyObjects) {
  builder.addFieldInt32(1, numReadyObjects, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaWaitReply.endPlasmaWaitReply = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaSubscribeRequest() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaSubscribeRequest}
 */
PlasmaSubscribeRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaSubscribeRequest=} obj
 * @returns {PlasmaSubscribeRequest}
 */
PlasmaSubscribeRequest.getRootAsPlasmaSubscribeRequest = function(bb, obj) {
  return (obj || new PlasmaSubscribeRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaSubscribeRequest.startPlasmaSubscribeRequest = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaSubscribeRequest.endPlasmaSubscribeRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaDataRequest() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaDataRequest}
 */
PlasmaDataRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaDataRequest=} obj
 * @returns {PlasmaDataRequest}
 */
PlasmaDataRequest.getRootAsPlasmaDataRequest = function(bb, obj) {
  return (obj || new PlasmaDataRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
PlasmaDataRequest.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
PlasmaDataRequest.prototype.address = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
PlasmaDataRequest.prototype.port = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaDataRequest.startPlasmaDataRequest = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
PlasmaDataRequest.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} addressOffset
 */
PlasmaDataRequest.addAddress = function(builder, addressOffset) {
  builder.addFieldOffset(1, addressOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} port
 */
PlasmaDataRequest.addPort = function(builder, port) {
  builder.addFieldInt32(2, port, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaDataRequest.endPlasmaDataRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
function PlasmaDataReply() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {PlasmaDataReply}
 */
PlasmaDataReply.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {PlasmaDataReply=} obj
 * @returns {PlasmaDataReply}
 */
PlasmaDataReply.getRootAsPlasmaDataReply = function(bb, obj) {
  return (obj || new PlasmaDataReply).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
PlasmaDataReply.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
PlasmaDataReply.prototype.objectSize = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
PlasmaDataReply.prototype.metadataSize = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
PlasmaDataReply.startPlasmaDataReply = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
PlasmaDataReply.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} objectSize
 */
PlasmaDataReply.addObjectSize = function(builder, objectSize) {
  builder.addFieldInt64(1, objectSize, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} metadataSize
 */
PlasmaDataReply.addMetadataSize = function(builder, metadataSize) {
  builder.addFieldInt64(2, metadataSize, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
PlasmaDataReply.endPlasmaDataReply = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.MessageType = MessageType;
this.PlasmaError = PlasmaError;
this.ObjectStatus = ObjectStatus;
this.PlasmaObjectSpec = PlasmaObjectSpec;
this.PlasmaCreateRequest = PlasmaCreateRequest;
this.PlasmaCreateReply = PlasmaCreateReply;
this.PlasmaAbortRequest = PlasmaAbortRequest;
this.PlasmaAbortReply = PlasmaAbortReply;
this.PlasmaSealRequest = PlasmaSealRequest;
this.PlasmaSealReply = PlasmaSealReply;
this.PlasmaGetRequest = PlasmaGetRequest;
this.PlasmaGetReply = PlasmaGetReply;
this.PlasmaReleaseRequest = PlasmaReleaseRequest;
this.PlasmaReleaseReply = PlasmaReleaseReply;
this.PlasmaDeleteRequest = PlasmaDeleteRequest;
this.PlasmaDeleteReply = PlasmaDeleteReply;
this.PlasmaStatusRequest = PlasmaStatusRequest;
this.PlasmaStatusReply = PlasmaStatusReply;
this.PlasmaContainsRequest = PlasmaContainsRequest;
this.PlasmaContainsReply = PlasmaContainsReply;
this.PlasmaConnectRequest = PlasmaConnectRequest;
this.PlasmaConnectReply = PlasmaConnectReply;
this.PlasmaEvictRequest = PlasmaEvictRequest;
this.PlasmaEvictReply = PlasmaEvictReply;
this.PlasmaFetchRequest = PlasmaFetchRequest;
this.ObjectRequestSpec = ObjectRequestSpec;
this.PlasmaWaitRequest = PlasmaWaitRequest;
this.ObjectReply = ObjectReply;
this.PlasmaWaitReply = PlasmaWaitReply;
this.PlasmaSubscribeRequest = PlasmaSubscribeRequest;
this.PlasmaDataRequest = PlasmaDataRequest;
this.PlasmaDataReply = PlasmaDataReply;
