/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sat Jan 13 19:09:50 2018. */

#include "event.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t EventRegister_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, EventRegister, events, events, &EventInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t EventInfo_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, EventInfo, id, id, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, EventInfo, name, id, 0),
    PB_FIELD(  3, UENUM   , OPTIONAL, STATIC  , OTHER, EventInfo, type, name, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, CALLBACK, OTHER, EventInfo, address, type, 0),
    PB_FIELD(  7, MESSAGE , OPTIONAL, STATIC  , OTHER, EventInfo, payload, address, &PayloadInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t PayloadInfo_fields[3] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, PayloadInfo, count, count, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, STATIC  , OTHER, PayloadInfo, data, count, &DataInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t DataInfo_fields[8] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, DataInfo, id, id, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, DataInfo, type, id, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, DataInfo, name, type, 0),
    PB_FIELD( 11, MESSAGE , OPTIONAL, STATIC  , OTHER, DataInfo, unit, name, &UnitInfo_fields),
    PB_FIELD( 12, MESSAGE , OPTIONAL, STATIC  , OTHER, DataInfo, min, unit, &Data_fields),
    PB_FIELD( 13, MESSAGE , OPTIONAL, STATIC  , OTHER, DataInfo, max, min, &Data_fields),
    PB_FIELD( 14, MESSAGE , OPTIONAL, STATIC  , OTHER, DataInfo, resolution, max, &Data_fields),
    PB_LAST_FIELD
};

const pb_field_t UnitInfo_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, UnitInfo, abbreviation, abbreviation, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, UnitInfo, name, abbreviation, 0),
    PB_LAST_FIELD
};

const pb_field_t EventStream_fields[7] = {
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , FIRST, EventStream, register, register, &EventRegister_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, EventStream, start_time, register, &google_protobuf_Timestamp_fields),
    PB_FIELD(  4, MESSAGE , REPEATED, CALLBACK, OTHER, EventStream, events, start_time, &Event_fields),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, EventStream, event_count, events, 0),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, EventStream, stop_time, event_count, &google_protobuf_Timestamp_fields),
    PB_FIELD(  7, STRING  , OPTIONAL, STATIC  , OTHER, EventStream, name, stop_time, 0),
    PB_LAST_FIELD
};

const pb_field_t Event_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Event, id, id, 0),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, Event, timestamp, id, &google_protobuf_Timestamp_fields),
    PB_FIELD(  7, MESSAGE , OPTIONAL, STATIC  , OTHER, Event, duration, timestamp, &google_protobuf_Duration_fields),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, Event, sequence, duration, 0),
    PB_FIELD( 11, MESSAGE , OPTIONAL, STATIC  , OTHER, Event, payload, sequence, &Payload_fields),
    PB_LAST_FIELD
};

const pb_field_t Payload_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, Payload, data, data, &Data_fields),
    PB_LAST_FIELD
};

const pb_field_t Data_fields[10] = {
    PB_ONEOF_FIELD(data_type,   1, MESSAGE , ONEOF, STATIC  , FIRST, Data, double_data, double_data, &google_protobuf_DoubleValue_fields),
    PB_ONEOF_FIELD(data_type,   2, MESSAGE , ONEOF, STATIC  , UNION, Data, float_data, float_data, &google_protobuf_FloatValue_fields),
    PB_ONEOF_FIELD(data_type,   3, MESSAGE , ONEOF, STATIC  , UNION, Data, int64_data, int64_data, &google_protobuf_Int64Value_fields),
    PB_ONEOF_FIELD(data_type,   4, MESSAGE , ONEOF, STATIC  , UNION, Data, uint64_data, uint64_data, &google_protobuf_UInt64Value_fields),
    PB_ONEOF_FIELD(data_type,   5, MESSAGE , ONEOF, STATIC  , UNION, Data, int32_data, int32_data, &google_protobuf_Int32Value_fields),
    PB_ONEOF_FIELD(data_type,   6, MESSAGE , ONEOF, STATIC  , UNION, Data, uint32_data, uint32_data, &google_protobuf_UInt32Value_fields),
    PB_ONEOF_FIELD(data_type,   7, MESSAGE , ONEOF, STATIC  , UNION, Data, bool_data, bool_data, &google_protobuf_BoolValue_fields),
    PB_ONEOF_FIELD(data_type,   8, MESSAGE , ONEOF, STATIC  , UNION, Data, string_data, string_data, &google_protobuf_StringValue_fields),
    PB_ONEOF_FIELD(data_type,   9, MESSAGE , ONEOF, STATIC  , UNION, Data, bytes_data, bytes_data, &google_protobuf_BytesValue_fields),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(EventRegister, events[0]) < 65536 && pb_membersize(EventInfo, payload) < 65536 && pb_membersize(PayloadInfo, data[0]) < 65536 && pb_membersize(DataInfo, unit) < 65536 && pb_membersize(DataInfo, min) < 65536 && pb_membersize(DataInfo, max) < 65536 && pb_membersize(DataInfo, resolution) < 65536 && pb_membersize(EventStream, register) < 65536 && pb_membersize(EventStream, start_time) < 65536 && pb_membersize(EventStream, stop_time) < 65536 && pb_membersize(Event, timestamp) < 65536 && pb_membersize(Event, duration) < 65536 && pb_membersize(Event, payload) < 65536 && pb_membersize(Payload, data[0]) < 65536 && pb_membersize(Data, data_type.double_data) < 65536 && pb_membersize(Data, data_type.float_data) < 65536 && pb_membersize(Data, data_type.int64_data) < 65536 && pb_membersize(Data, data_type.uint64_data) < 65536 && pb_membersize(Data, data_type.int32_data) < 65536 && pb_membersize(Data, data_type.uint32_data) < 65536 && pb_membersize(Data, data_type.bool_data) < 65536 && pb_membersize(Data, data_type.string_data) < 65536 && pb_membersize(Data, data_type.bytes_data) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_EventRegister_EventInfo_PayloadInfo_DataInfo_UnitInfo_EventStream_Event_Payload_Data)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(EventRegister, events[0]) < 256 && pb_membersize(EventInfo, payload) < 256 && pb_membersize(PayloadInfo, data[0]) < 256 && pb_membersize(DataInfo, unit) < 256 && pb_membersize(DataInfo, min) < 256 && pb_membersize(DataInfo, max) < 256 && pb_membersize(DataInfo, resolution) < 256 && pb_membersize(EventStream, register) < 256 && pb_membersize(EventStream, start_time) < 256 && pb_membersize(EventStream, stop_time) < 256 && pb_membersize(Event, timestamp) < 256 && pb_membersize(Event, duration) < 256 && pb_membersize(Event, payload) < 256 && pb_membersize(Payload, data[0]) < 256 && pb_membersize(Data, data_type.double_data) < 256 && pb_membersize(Data, data_type.float_data) < 256 && pb_membersize(Data, data_type.int64_data) < 256 && pb_membersize(Data, data_type.uint64_data) < 256 && pb_membersize(Data, data_type.int32_data) < 256 && pb_membersize(Data, data_type.uint32_data) < 256 && pb_membersize(Data, data_type.bool_data) < 256 && pb_membersize(Data, data_type.string_data) < 256 && pb_membersize(Data, data_type.bytes_data) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_EventRegister_EventInfo_PayloadInfo_DataInfo_UnitInfo_EventStream_Event_Payload_Data)
#endif


/* @@protoc_insertion_point(eof) */
